### ISSUE TITLE
Data scraping is not allowed on Card Explorer JP/SG server

### ISSUE THREAD

**Issue by NijiharaTsubasa** [wingyintang/LLSIF_simulator#1]
hi, I'm NijiharaTsubasa, the developer of LLSIF Card Explorer.
I'm here to tell you that data scraping is not allowed on Card Explorer JP / SG server (card.llsif.moe / c.1994.io / card.llsupport.cn) for various reasons (mainly because of high server load it may cause).

You should only scrap data from the CN server c.dash.moe . Please remove the other ones from your code ASAP.

**Comment by wingyintang** [comment]
Okay, the changes have been made.
